services:
  mongodb:
    container_name: mongo-service
    image: mongo
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend-wanderlust
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "31100:8080"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    container_name: frontend-wanderlust
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started

  redis:
    container_name: redis-service
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5  
