apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: wanderlust
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/redis
