name: CI-CD

on:
  push:
    branches:
      - jibrankhan

  pull_request:
    branches:
      - jibrankhan

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Start Backend Services
        run: |
          docker compose up -d mongodb redis backend
          sleep 15

      - name: Seed Test Data
        run: docker compose exec -T backend node seed-test-data.js

      - name: Run Linter
        working-directory: frontend
        run: npm run lint

      - name: Run Unit Tests
        working-directory: frontend
        run: npm test -- --watchAll=false __tests__/App.test.tsx

      - name: Run Integration Tests
        working-directory: frontend
        run: npm test -- --watchAll=false __tests__/integration/home.test.tsx

      - name: Build Docker Image
        run: docker build -t frontend ./frontend

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Run Unit Tests
        working-directory: backend
        run: npx jest tests/unit --runInBand --watchAll=false

      - name: Build Docker Image
        run: docker build -t wanderlust-backend ./backend

  deploy:
    name: Deployment Status
    runs-on: ubuntu-latest

    needs:
      - frontend
      - backend

    steps:
      - name: Deployment Status
        run: echo "Deployment Completed Successfully"
